### ISSUE TITLE
Unhandled Rejection Error: Cannot find ffprobe

### ISSUE THREAD

**Issue by memayank00** [volumenetwork/video-thumbnail-generator#6]
when i install this module and try to execute code then it's says that  "Unhandled Rejection Error: Cannot find ffprobe"

**Comment by irvingswiftj** [comment]
This is the same as: https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/issues/691

Have you checked that you have ffmpeg installed in your environment ?

**Comment by irvingswiftj** [comment]
Is this still an issue @memayank00 ? Else can I close this ticket?

**Comment by saeedmashhadi** [comment]
I have same issue. also [fluent-ffmpeg](https://www.npmjs.com/package/fluent-ffmpeg) installed.

**Comment by Vishnupriya112** [comment]
Same Problem .. I have installed fluent-ffmpeg eventhough am getting this error

**Comment by irvingswiftj** [comment]
you do not need to install fluent-ffmpeg as it is already a dependency of this project. However you need to make sure that you have ffmpeg installed: https://github.com/adaptlearning/adapt_authoring/wiki/Installing-FFmpeg

**Comment by Vishnupriya112** [comment]
```
var tg = new ThumbnailGenerator({
                    sourcePath: main_folder_path,
                    // thumbnailPath: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/',
                    tmpDir: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/' //only required if you can't write to /tmp/ and you need to generate gifs
                  });
                  console.log(tg)
                //   tg.generate()
                //   .then("console.log");
                  tg.generate((err, result) => {
                    if(err){
                        console.log(err)
                    }
                    else{
                        console.log(result)
                    }
                  })
```


Error : 

Unhandled rejection Error: Cannot find ffprobe
```
    at E:\sri\new\vishnu\phase_2\node_modules\video-thumbnail-generator\node_modules\fluent-ffmpeg\lib\ffprobe.js:145:31
    at E:\sri\new\vishnu\phase_2\node_modules\video-thumbnail-generator\node_modules\fluent-ffmpeg\lib\capabilities.js:194:9
    at E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:356:16
    at nextTask (E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:5057:29)
    at E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:5064:13
    at apply (E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:21:25)
    at E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:56:12
    at E:\sri\new\vishnu\phase_2\node_modules\async\dist\async.js:840:16
    at E:\sri\new\vishnus\phase_2\node_modules\video-thumbnail-generator\node_modules\fluent-ffmpeg\lib\capabilities.js:183:15
    at FSReqWrap.cb [as oncomplete] (fs.js:312:19)
```

**Comment by irvingswiftj** [comment]
ok, I had never tried running this on Windows and do not have access to even a windows VM at the moment to attempt to fix.

**Comment by Vishnupriya112** [comment]
Ok then shall  I try in Linux ?

**Comment by irvingswiftj** [comment]
I don't see why it wouldn't run on Windows if ffmpeg is installed, but, i have it working here on both OSX and linux (ubuntu)

**Comment by Vishnupriya112** [comment]
In Linux also am getting the same error

**Comment by irvingswiftj** [comment]
did you install ffmpeg?

**Comment by Vishnupriya112** [comment]
Yes I have installed

**Comment by irvingswiftj** [comment]
what happens when you run `ffmpeg` and `ffprobe` from your terminal?

This is what I get:
```
james@Jamess-MacBook-Pro:~|⇒  ffprobe
ffprobe version 3.4.2 Copyright (c) 2007-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --disable-jack --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Simple multimedia streams analyzer
usage: ffprobe [OPTIONS] [INPUT_FILE]

You have to specify one input file.
Use -h to get full help or, even better, run 'man ffprobe'.
james@Jamess-MacBook-Pro:~|⇒  ffmpeg
ffmpeg version 3.4.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.4.2 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --disable-jack --enable-gpl --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by Vishnupriya112** [comment]
I have tried this

$ ls node_modules/ffprobe
LICENSE  README.md  index.js  package.json  test

Am getting like this

**Comment by Vishnupriya112** [comment]
I don't have bin directory inside ffmpeg.. Is that cause problem

**Comment by irvingswiftj** [comment]
try doing a `sudo apt update` before doing a `sudo apt install ffmpeg`

**Comment by irvingswiftj** [comment]
Closing issue as it has nothing to do with video-thumbnail-generator and is due to ffmpeg not being installed on the computer/server.

**Comment by Vishnupriya112** [comment]
Thank you so much much Now am not getting that error. But its showing path must be a String.

My code is : 
```

var tg = new ThumbnailGenerator({
                    sourcePath: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/'+filename,
                    // thumbnailPath: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/',
                    tmpDir: pro_root_path+'public/uploads/inspection/'+req.body.clientID+'/images/' //only required if you can't write to /tmp/ and you need to generate gifs
                  });
     
                  tg.generate((err, result) => {
                    if(err){
                        console.log(err)
                    }
                    else{
                        console.log(result)
                    }
                  })
```

**Comment by Vishnupriya112** [comment]
Thank you so much its working... But Its Taking long time to generate

**Comment by albert2102** [comment]
> Ok then shall I try in Linux ?

you can run on windows,
1- first you must run ffmpeg and make environment variables you can see this  link to  do it 
https://www.wikihow.com/Install-FFmpeg-on-Windows#/Image:Install-FFmpeg-on-Windows-Step-5-Version-4.jpg
2-you must run it on cmd not powershell

**Comment by AlankrithaShekar** [comment]
@albert2102 i have ffmpeg installed and have done exactly as mentioned in the link, despite that i get the same error -unhandled rejections
