### ISSUE TITLE
generateGif issue

### ISSUE THREAD

**Issue by srinivasnamashivaya** [volumenetwork/video-thumbnail-generator#8]
I am unable to generate Gif and I am getting following error:
```
Unhandled rejection Error: ffmpeg exited with code 1: av_interleaved_write_frame(): Input/output error
frame=    1 fps=0.6 q=-0.0 Lsize=N/A time=00:00:00.10 bitrate=N/A speed=0.0646x    
video:1kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Conversion failed!

    at ChildProcess.<anonymous> (/Applications/MAMP/htdocs/video-thumbnail-generator/thumb/node_modules/fluent-ffmpeg/lib/processor.js:177:22)
    at ChildProcess.emit (events.js:196:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
```

FYI: tg.generate() is working fine.

**Comment by Lorem96** [comment]
Have the same error: 

Enviroment
- Win 10
- ffmpeg version git-2020-03-15-c467328
- video-thumbnail-generator: 1.1.3

Video 
- Mime Type: video/mp4
- Codec Long Name: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10

**Comment by ahmedmagdy11** [comment]
did you find the solution?
